#!/bin/sh

export XSECURELOCK_SAVER=saver_mpv
export XSECURELOCK_FONT="Hack Regular"
export XSECURELOCK_BLANK_TIMEOUT=2
export XSECURELOCK_LIST_VIDEOS_COMMAND="find $HOME/.github/lock.jpg -type f"
export XSECURELOCK_IMAGE_DURATION_SECONDS=60

/usr/bin/xsecurelock
