#!/bin/sh
# Inspired by @Lokesh-krishna
# Uses PandorasFox/i3lock-color

i3lock -neti ~/.github/lock.jpg \
    --redraw-thread \
    --linecolor=00000000             \
    --keyhlcolor=eceff4              \
    --bshlcolor=d8dee9ff             \
    --separatorcolor=00000000        \
    --radius=300                     \
                                     \
    --insidevercolor=00000000        \
    --insidewrongcolor=00000000      \
    --insidecolor=00000000           \
                                     \
    --ringcolor=8fbcbb               \
    --ringvercolor=ebcb8bff          \
    --ringwrongcolor=bf616aff        \
                                     \
    --clock                          \
    --timecolor=eceff4ff             \
    --timestr="%H:%M"                \
    --time-font=Hack                 \
    --timesize=134                   \
                                     \
    --datecolor=d8dee9ff             \
    --datestr="%A, %d %B"            \
    --date-font=Hack                 \
    --datesize=30                    \
                                     \
    --veriftext="Verifying..."       \
    --verif-font=Hack                \
    --verifcolor=d8dee9ff            \
    --verifsize=45                   \
                                     \
    --wrongtext="Incorrect"          \
    --wrong-font=Hack                \
    --wrongcolor=d8dee9ff            \
    --wrongsize=45                   \
    --noinputtext="No input"         \
                                     \
    --indicator                      \
    --color=2e3440
