#!/bin/sh
# Dependencies: pandoc, wkhtmltopdf

INPUT=$1
BASENAME=$(basename "${INPUT}")
OUTPUT="/tmp/$(basename "${INPUT}").pdf"

# Check if input exists
if [ -z "${INPUT}" ] ; then
    echo "Please specify one file"
    exit 1
elif [ ! -f "${INPUT}" ]; then
    echo "File does not exist"
    exit 1
fi

# Change to respective directory to resolve images
cd "$(dirname "$(realpath "${INPUT}")")" \
    || (echo "Failed to change directory" && exit 1)

# Run pandoc
pandoc --quiet                                  \
    -H "${XDG_CONFIG_HOME}/pandoc/gh_md.css"    \
    -V papersize=a4                             \
    -V margin-top=16                            \
    -V margin-bottom=16                         \
    -V margin-left=0                            \
    -V margin-right=0                           \
    -f markdown                                 \
    -t html                                     \
    --mathjax                                   \
    -s "${BASENAME}"                            \
    -o "${OUTPUT}"

# Get PID
PID=$(pgrep -a mupdf | grep "${BASENAME}" | cut -d " " -f1)

# If mupdf is already running, refresh the file. Otherwise start mupdf
if [ -n "${PID}" ]; then
    kill -HUP "${PID}"
else
    mupdf "${OUTPUT}" &
fi
