# Shell aliases
alias :q='exit'
alias ls='ls --color=always'
alias la='ls -hal'
alias lai='ls -hail'
alias ip='ip --color'
alias ranger='ranger --choosedir=$HOME/.rangerdir; LASTDIR=`cat $HOME/.rangerdir`; cd "$LASTDIR"'
alias clock='tty-clock -c'

alias gs='git status'
alias ga='git add'
alias gd='git diff'
alias gc='git commit'
alias gca='git commit -a'
alias gf='git fetch'
alias gp='git pull'
alias gP='git push'

alias v='vagrant'
alias vs='vagrant ssh'
alias vu='vagrant up'
alias vh='vagrant halt'
alias vr='vagrant reload'
alias vd='vagrant destroy'
